#include <lexical/lexicaltable.h>
/*
 typedef struct {
    U64 curr;
    struct {
        enum {
            VALUE_RAW,
            VALUE_CATEGORY
        } type;
        U8 value;
    } input;
    U64 next;
} transrule;
 */
U64 lexicaltable_hint[] = {
    0,32
};
transrule lexicaltable[] = {
    {0,{VALUE_RAW,'b'},1},
    {0,{VALUE_RAW,'c'},5},
    {0,{VALUE_RAW,'i'},9},
    {0,{VALUE_RAW,'l'},12},
    {0,{VALUE_RAW,'s'},16},
    {0,{VALUE_RAW,'u'},21},
    {0,{VALUE_RAW,'r'},71},
    {0,{VALUE_RAW,'$'},29},
    {0,{VALUE_RAW,'>'},30|ACCEPTED},
    {0,{VALUE_RAW,'<'},31|ACCEPTED},
    {0,{VALUE_RAW,'='},32|ACCEPTED},
    {0,{VALUE_RAW,'!'},37|ACCEPTED},
    {0,{VALUE_RAW,'+'},39|ACCEPTED},
    {0,{VALUE_RAW,'-'},40|ACCEPTED},
    {0,{VALUE_RAW,'*'},41|ACCEPTED},
    {0,{VALUE_RAW,'/'},42|ACCEPTED},
    {0,{VALUE_RAW,'&'},43|ACCEPTED},
    {0,{VALUE_RAW,'|'},44|ACCEPTED},
    {0,{VALUE_RAW,'~'},45|ACCEPTED},
    {0,{VALUE_RAW,'\''},49|ACCEPTED},
    {0,{VALUE_RAW,'\"'},50|ACCEPTED},
    {0,{VALUE_RAW,','},51|ACCEPTED},
    {0,{VALUE_RAW,'@'},52|ACCEPTED},
    {0,{VALUE_RAW,';'},53|ACCEPTED},
    {0,{VALUE_RAW,'{'},54|ACCEPTED},
    {0,{VALUE_RAW,'['},55|ACCEPTED},
    {0,{VALUE_RAW,'('},56|ACCEPTED},
    {0,{VALUE_RAW,')'},57|ACCEPTED},
    {0,{VALUE_RAW,']'},58|ACCEPTED},
    {0,{VALUE_RAW,'}'},59|ACCEPTED},
    {0,{VALUE_CATEGORY,CATEGORY_DIGIT},77|ACCEPTED},
    {0,{VALUE_CATEGORY,CATEGORY_CHARACTER},78|ACCEPTED},
    {1,{VALUE_RAW,'y'},2},
    {1,{VALUE_CATEGORY,CATEGORY_DIGIT},78|ACCEPTED},
    {1,{VALUE_CATEGORY,CATEGORY_CHARACTER},78|ACCEPTED},
    {2,{VALUE_RAW,'t'},3},
    {2,{VALUE_CATEGORY,CATEGORY_DIGIT},78|ACCEPTED},
    {2,{VALUE_CATEGORY,CATEGORY_CHARACTER},78|ACCEPTED},
    {3,{VALUE_RAW,'e'},4|ACCEPTED},
    {3,{VALUE_CATEGORY,CATEGORY_DIGIT},78|ACCEPTED},
    {3,{VALUE_CATEGORY,CATEGORY_CHARACTER},78|ACCEPTED},
    {4,{VALUE_CATEGORY,CATEGORY_DIGIT},78|ACCEPTED},
    {4,{VALUE_CATEGORY,CATEGORY_CHARACTER},78|ACCEPTED},
    {5,{VALUE_RAW,'h'},6},
    {5,{VALUE_CATEGORY,CATEGORY_DIGIT},78|ACCEPTED},
    {5,{VALUE_CATEGORY,CATEGORY_CHARACTER},78|ACCEPTED},
    {6,{VALUE_RAW,'a'},7},
    {6,{VALUE_CATEGORY,CATEGORY_DIGIT},78|ACCEPTED},
    {6,{VALUE_CATEGORY,CATEGORY_CHARACTER},78|ACCEPTED},
    {7,{VALUE_RAW,'r'},8|ACCEPTED},
    {7,{VALUE_CATEGORY,CATEGORY_DIGIT},78|ACCEPTED},
    {7,{VALUE_CATEGORY,CATEGORY_CHARACTER},78|ACCEPTED},
    {8,{VALUE_CATEGORY,CATEGORY_DIGIT},78|ACCEPTED},
    {8,{VALUE_CATEGORY,CATEGORY_CHARACTER},78|ACCEPTED},
};

